### ISSUE TITLE
Stitch API error

### ISSUE THREAD

**Issue by SeanFLynch** [singer-io/tap-bing-ads#16]
Hi,

We keep getting the following error when running the Stitch tap:

"2018-03-01 09:12:55,722Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "Error running AdGroupPerformanceReport report". Target succeeded."

Any ideas?

Sean.

**Comment by KAllan357** [comment]
Hi @SeanFLynch, I looked you up in our system - usually the logs in the Stitch UI will reveal a bit more context. Here's what I found:

```
2018-03-02 10:39:31,697Z    tap - CRITICAL Errors during transform
2018-03-02 10:39:31,697Z    tap - 	last_login: 0000-00-00 00:00:00 does not match {'type': ['string', 'null'], 'format': 'date-time'}
```

We're using some Python code to transform the value Pipedrive is returning into a datetime object. In this case, its failing to parse a string `"0000-00-00 00:00:00"` into a datetime.

The easiest path forward would be to modify the offending row in Pipedrive or to deselect that `last_login` column in Stitch.

**Comment by KAllan357** [comment]
Hi @SeanFLynch, I see some logging that indicates one of the reports failed. I'm not sure of the reason, that would take some more debugging:

```
2018-03-02 09:13:00,838Z    tap - Exception: Error running AdGroupPerformanceReport report
2018-03-02 09:13:01,016Z    tap - INFO "generate_report" job took 0.5s, ended with status "failed"
```
It looks like the report's status comes back as "Failed" which is documented by Bing as:

> An error occurred while generating the report. You will need to submit your report request again. If the request continues to fail, consider getting the tracking identifier from the response message and contacting support.

https://docs.microsoft.com/en-us/bingads/reporting-service/reportrequeststatustype

**Comment by KAllan357** [comment]
Opening an issue to add logging so we can see the report tracking identifier: https://github.com/singer-io/tap-bing-ads/issues/17
